### ISSUE TITLE
Update to 3.3.7 version

### ISSUE THREAD

**Issue by g0blin79** [douglasmiranda/docker-taiga#10]
Update to the 3.3.7 version of Taiga BE and FE-dist (events does not have releases...)

**Comment by g0blin79** [comment]
@douglasmiranda are you planning to merge this issue and (more in general) to keep this project maintained? In my company we tried Taiga as Agile project management tool in some "pilot" projects since last July. We used your work to install Taiga in our Kubernetes infrastracture on Google Cloud and we are really interested in this project, 'cause we are planning to adopt Taiga in a more "official" way in the next months.

Regarding that, we could help you to keep this project updated. 

Then, let us know 😄

**Comment by douglasmiranda** [comment]
I'll merge. =]

Thank you for offering to help me with this, it means a lot!

And if that's the case I'll ping you when discussing new things to do in this project, is that ok?

**Comment by g0blin79** [comment]
Sounds good.

If I’ll start to work on some update to my Taiga instance (for example, we are planning to update to 4.x version, released some weeks ago), I’ll contact you.

Bye
Daniele


Daniele Piaggesi

Mobile: +39 393 880 78 50
Skype: g0blin79
E-mail: daniele.piaggesi@bmeme.com
------------------------------------------
Bonsaimeme S.r.l.
Via del Porto Fluviale, 9
00154 Roma - Italy

Phone:  +39 06 98 26 04 39 
Fax:  +39 06 94 81 02 03
-------------------------------------------
bmeme.com <http://bmeme.com/>


*** Prima di stampare, pensa all'ambiente! ***
*** Before printing think about environment and costs ***


Le informazioni, i dati e le notizie contenute nella presente comunicazione e i relativi allegati sono di natura privata e come tali possono essere riservate e sono, comunque, destinate esclusivamente ai destinatari indicati in epigrafe. La diffusione, distribuzione e/o la copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi dell’art. 616 c.p., sia ai sensi del D.Lgs. n. 196/2003. Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di darcene immediata comunicazione anche inviando un messaggio all’indirizzo email:  info@bonsaimeme.com <mailto:info@bonsaimeme.com>. Il testo della email potrebbe contenere opinioni personali e non necessariamente riconducibili a quelle di Bonsaimeme S.r.l.

--- --- ---

This e-mail (including attachments) is intended only for the recipient(s) named above. It may contain confidential or privileged information and should not be read, copied or otherwise used by any other person. If you are not the named recipient, please contact: info@bonsaimeme.com <mailto:info@bonsaimeme.com> and delete the e-mail from your system. Rif. D.L. 196/2003.
